Repository sonatype-nexus-community/contribute.sonatype.com, pull requests merged in 2024-08, with the labels that each got.

#17 feat: Identify and separate our Graduated projects
  .github/workflows/ci.yaml
  assets/scss/_styles_project.scss
  assets/scss/_variables_project_after_bs.scss
  content/en/projects/graduated/_index.md
  data/projects/all.json
  layouts/partials/projects/card.html
  layouts/projects/list.html
Labels: documentation, :heart_eyes: cla signed

#18 feat: final boilerplate removal
  assets/icons/logo.svg
  content/en/_index.md
  content/en/about/index.md
  content/en/projects/active/_index.md
  content/en/projects/flagship/_index.md
  hugo.yaml
Labels: documentation, :heart_eyes: cla signed

#19 Move security/bug banner to bottom
  content/en/docs/contributing/reporting-issues.md
Labels: :heart_eyes: cla signed

#20 feat: add consent warning for Google Analytics
  data/consent.yaml
  layouts/_default/baseof.html
  layouts/partials/consent.html
Labels: enhancement, :heart_eyes: cla signed
