Repository sonatype-nexus-community/contribute.sonatype.com, pull requests merged in 2024-09, with the labels that each got.

#21 docs: Added new content and fixed a link
  content/en/_index.md
  content/en/docs/standards/dependency-management.md
  content/en/docs/standards/secrets-management.md
Labels: bug, enhancement, :heart_eyes: cla signed

#24 doc: removed boilerplate content
  content/en/docs/standards/_index.md
Labels: documentation, :heart_eyes: cla signed

#28 Added links to roles from other docs
  README.md
  content/en/docs/contributing/discussing-ideas.md
  content/en/docs/contributing/reporting-issues.md
  content/en/docs/contributing/submitting.md
  content/en/docs/new-project/_index.md
Labels: :unamused: commits missing author, :anguished: commits missing verification
